name: quest_game_manager
description: A Meta Quest app for browsing, downloading, and installing Quest games.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:


  cached_network_image: ^3.3.0
  crypto: ^3.0.3
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.0
  json_annotation: ^4.8.0
  path: ^1.9.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
